api/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers

from . import views

router = routers.SimpleRouter(trailing_slash=True)

router.register(r'articles', views.ArticleViewSet, 'articles')

urlpatterns = [
    url(r'^', include(router.urls)),
]

core/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls import handler404, handler500
from .views import custom_handler404, custom_handler500

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='news:articles_list')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^admin/', admin.site.urls),
    url(r'^errors/404/$', custom_handler404, name='error-404'),
    url(r'^errors/500/$', custom_handler500, name='error-500'),
]

handler404 = custom_handler404
handler500 = custom_handler500

news/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

app_name = 'news'

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='news:articles_list')),
    url(r'^articles/$', views.ArticlesList.as_view(), name='articles_list'),
    url(r'^articles/(?P<pk>\d+)/$', views.ArticleDetail.as_view(), name='article_detail'),
    url(r'^articles/create/$', views.ArticleCreate.as_view(), name='article_create'),
    url(r'^articles/(?P<pk>\d+)/update/$', views.ArticleUpdate.as_view(), name='article_update'),
    url(r'^articles/(?P<pk>\d+)/delete/$', views.ArticleDelete.as_view(), name='article_delete'),
    ]

api/models.py
# -*- coding: utf-8 -*-

from django.db import models

class Article(models.Model):
    class Meta:
        verbose_name_plural = 'articles'

    title = models.CharField(
        max_length=100,
        verbose_name="title"
        )
    description = models.TextField(
        verbose_name="decription"
        )
    is_published = models.BooleanField(
        default=False,
        verbose_name = "is published"
        )
    publication_date =  models.DateTimeField(
        verbose_name = "publication date"
        )

    def __str__(self):
        return self.title

news/models.py
# -*- coding: utf-8 -*-

from django.db import models

# Create your models here.

news/forms.py
# -*- coding: utf-8 -*-

import datetime

from django import forms
from datetimewidget.widgets import DateTimeWidget

dateTimeWidgetOptions = {
    'format': 'yyyy-mm-dd HH:ii',
    'autoclose': True,
    'showMeridian' : False
    }

class ArticleForm(forms.Form):

    title = forms.CharField(
        max_length=100,
        label="Title",
        required=True
        )
    description = forms.CharField(
        label="Description",
        required=True,
        widget=forms.Textarea
        )
    is_published = forms.BooleanField(
        initial=True,
        label = "Published",
        required=False
        )
    publication_date =  forms.DateTimeField(
        initial=datetime.datetime.now,
        label = "Publication date",
        required=True,
        widget=DateTimeWidget(
            options = dateTimeWidgetOptions,
            bootstrap_version=3
            )
        )

api/views.py
from rest_framework import viewsets
from .models import Article
from .serializers import ArticleSerializer
from .permissions import ApiAccessPermission

class ArticleViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows articles to be viewed or edited.
    """
    queryset = Article.objects.all().order_by('-publication_date')
    serializer_class = ArticleSerializer

core/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _


def custom_handler404(request):
    return render(request, '404.html')


def custom_handler500(request):
    return render(request, '500.html')

news/views.py
# -*- coding: utf-8 -*-

import logging
LOGGER = logging.getLogger(__name__)

import functools

from django.conf import settings
from django.shortcuts import render, redirect
from django.views import View
from django.http import Http404

from .forms import ArticleForm

from django.views.generic.edit import FormView

from . import api_services


def processExceptions(func):
    """
    Intercepts and logs exceptions which may be raised
    during view processing
    """

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except api_services.UnexpectedApiResponse as e:
            LOGGER.exception(e)
            if e.response_status_code == 404:
                raise Http404
            raise
        except Exception as e:
            LOGGER.exception(e)
            raise
    return wrapper


class ArticlesList(View):
    @processExceptions
    def get(self, request):
        articles = api_services.get_articles()
        context = {
            "page_title": "Dashboard",
            "articles": articles
            }
        return render(request, 'news/articles_list.html', context)


class ArticleDetail(View):
    @processExceptions
    def get(self, request, pk):
        article = api_services.get_article(pk)
        context = {
            "page_title": "Detail : %s" % article["title"],
            "article": article
            }
        return render(request, 'news/article_detail.html', context)


class ArticleCreate(FormView):

    template_name = 'news/article_create.html'
    form_class = ArticleForm

    @processExceptions
    def form_valid(self, form):
        article = data=form.cleaned_data
        id = api_services.create_article(article)
        return redirect("news:article_detail", pk=id)

    def get_context_data(self, **kwargs):
        context = super(ArticleCreate, self).get_context_data(**kwargs)
        context['page_title'] = "Article creation"
        return context


class ArticleUpdate(FormView):

    template_name = 'news/article_update.html'
    form_class = ArticleForm

    @processExceptions
    def get_initial(self):
        initial = super(ArticleUpdate, self).get_initial()
        self.article = api_services.get_article(self.kwargs['pk'])
        initial.update(self.article)
        return initial

    def get_context_data(self, **kwargs):
        context = super(ArticleUpdate, self).get_context_data(**kwargs)
        context['page_title'] = "Article update : %s" % self.article["title"]
        context['article'] = self.article
        return context

    @processExceptions
    def form_valid(self, form):
        article = data=form.cleaned_data
        id = api_services.update_article(self.kwargs['pk'], article)
        return redirect("news:article_detail", pk=self.kwargs['pk'])


class ArticleDelete(View):
    @processExceptions
    def get(self, request, pk):
        article = api_services.get_article(pk)
        context = {
            "page_title": "Article deletion : %s" % article["title"],
            "article": article
            }
        return render(request, 'news/article_delete.html', context)

    @processExceptions
    def post(self, request, pk):
        api_services.delete_article(pk)
        return redirect("news:articles_list")

news/templates/news/article_create.html
{% extends "news/news-base.html" %}
{% load static %}

{% block extrahead %}
 {{ block.super }}
<script src="{% static 'jquery/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{{ form.media }}
{% endblock extrahead %}

{% block news_container %}

<div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12">

    <div class="row">
        <div class="col-md-8 col-md-offset-4 article-action">
            <h1>New article</h1>
        </div>
    </div>

    <form id="create-article-form" method="post">

        {% csrf_token %}

        {% include "news/article_form.html" %}

        <div class="form-group row">
            <div class="col-md-8 col-md-offset-4">
                <div class="row">
                    <div class="col-md-3 col-md-offset-5 col-sm-3 col-sm-offset-5 col-xs-12">
                        <span class="btns-containers pull-right">
                            <a href="{% url 'news:articles_list' %}" class="btn btn-secondary">Cancel</a>
                        </span>
                    </div>
                    <div class="col-md-4 col-sm-3 col-xs-12">
                        <span class="btns-containers pull-right">
                            <input class="btn btn-danger" id="create-article-form-submit" type="submit" value="Create article" />
                        </span>
                    </div>
                </div>
            </div>
        </div>

    </form>

</div>

{% endblock news_container %}

{% block extrafoot %}
{% comment %}
Empty because the jquery / bootstrap .js file have already been loaded in the extrahead block
{% endcomment %}
{% endblock extrafoot %}

news/templates/news/article_delete.html
{% extends "news/news-base.html" %}
{% load static %}

{% block news_container %}

<div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12">

    <div class="row">
        <div class="col-md-8 col-md-offset-4 article-action">
            <h1>Confirm article deletion ?</h1>
        </div>
    </div>

    {% include "news/article_preview.html" %}

    <div class="row">
        <form id="delete-article-form" method="post">

            {% csrf_token %}

            <div class="row">
                <div class="col-md-8 col-md-offset-4">
                    <div class="row">
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <span class="btns-containers">
                                <a href="{% url 'news:article_detail' article.id %}" class="btn btn-secondary">Cancel</a>
                            </span>
                        </div>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                            <span class="btns-containers">
                                <input class="btn btn-danger" id="delete-article-form-submit" type="submit" value="Delete this article" />
                            </span>
                        </div>
                    </div>
                </div>
            </div>

        </form>

    </div>

</div>

{% endblock news_container %}

news/templates/news/article_detail.html
{% extends "news/news-base.html" %}
{% load static %}

{% block news_container %}

<div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12">

    <div class="row">
        <div class="col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-4 col-xs-12 article-action">
            <h1>Article detail</h1>
        </div>
    </div>

    {% include "news/article_preview.html" %}

    <div class="row article-row">
        <div class="col-md-4 col-sm-4 col-xs-12 article-field-name"></div>
        <div class="col-md-8 col-sm-8 col-xs-12">
            <span class="btns-containers">
                <a href="{% url 'news:article_update' article.id %}" class="btn btn-warning">Update this article</a>
            </span>
            <span class="btns-containers">
                <a href="{% url 'news:article_delete' article.id %}" class="btn btn-warning">Delete this article</a>
            </span>
            <span class="btns-containers">
                <a href="{% url 'news:articles_list' %}" class="btn btn-info">Back to dashboard</a>
            </span>
        </div>
    </div>

</div>

{% endblock news_container %}

news/templates/news/article_form.html
{% load static %}
{% load widget_tweaks %}

{% if form.non_field_errors %}
<div class="row">
    <div class="col-md-8 col-md-offset-2 validation-error">
        {{ form.non_field_errors }}
    </div>
</div>
{% endif %}

<div class="form-group row">
    <label class="col-md-4 col-form-label" for="{{ form.title.id_for_label }}">
    {{ form.title.label }} *
    </label>
    <div class="col-md-8">
    {{ form.title|add_class:"form-control" }}
    </div>
    {% if form.title.errors %}
    <div class="col-md-8 col-md-offset-4 validation-error">{{ form.title.errors }}</div>
    {% endif %}
</div>

<div class="form-group row">
    <label class="col-md-4 col-form-label" for="{{ form.description.id_for_label }}">
    {{ form.description.label }} *
    </label>
    <div class="col-md-8">
    {{ form.description|add_class:"form-control" }}
    </div>
    {% if form.description.errors %}
    <div class="col-md-8 col-md-offset-4 validation-error">{{ form.description.errors }}</div>
    {% endif %}
</div>

<div class="form-group row">
    <label class="col-md-4 col-form-label" for="{{ form.is_published.id_for_label }}">
    {{ form.is_published.label }} *
    </label>
    <div class="col-md-8">
        <span class="pull-left">
        {{ form.is_published|add_class:"form-control" }}
        </span>
    </div>
    {% if form.is_published.errors %}
    <div class="col-md-8 col-md-offset-4 validation-error">{{ form.is_published.errors }}</div>
    {% endif %}
</div>

<div class="form-group row">
    <label class="col-md-4 col-form-label" for="{{ form.publication_date.id_for_label }}">
    {{ form.publication_date.label }} *
    </label>
    <div class="col-md-8">
    {{ form.publication_date|add_class:"form-control" }}
    </div>
    {% if form.publication_date.errors %}
    <div class="col-md-8 col-md-offset-4 validation-error">{{ form.publication_date.errors }}</div>
    {% endif %}
</div>

news/templates/news/article_preview.html
{% load static %}

<div class="row article-view">

    <div class="row article-row">
        <div class="col-md-4 col-sm-4 col-xs-12 article-field-name">Title&nbsp;:</div>
        <div class="col-md-8 col-sm-8 col-xs-12 article-field-value">{{ article.title }}</div>
    </div>

    <div class="row article-row">
        <div class="col-md-4 col-sm-4 col-xs-12 article-field-name">Description&nbsp;:</div>
        <div class="col-md-8 col-sm-8 col-xs-12 article-field-value">{{ article.description }}</div>
    </div>

    <div class="row article-row">
        <div class="col-md-4 col-sm-4 col-xs-12 article-field-name">Published&nbsp;:</div>
        <div class="col-md-8 col-sm-8 col-xs-12 article-field-value">
            {% if article.is_published %}
            Yes
            {% else %}
            No
            {% endif %}
        </div>
    </div>

    <div class="row article-row">
        <div class="col-md-4 col-sm-4 col-xs-12 article-field-name">Publication date&nbsp;:</div>
        <div class="col-md-8 col-sm-8 col-xs-12 article-field-value">{{ article.publication_date }}</div>
    </div>

</div>

news/templates/news/article_update.html
{% extends "news/news-base.html" %}
{% load static %}

{% block extrahead %}
 {{ block.super }}
<script src="{% static 'jquery/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{{ form.media }}
{% endblock extrahead %}

{% block news_container %}

<div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12">

    <div class="row">
        <div class="col-md-8 col-md-offset-4 article-action">
            <h1>Update article</h1>
        </div>
    </div>

    <form id="update-article-form" method="post">

        {% csrf_token %}

        {% include "news/article_form.html" %}

        <div class="form-group row">
            <div class="col-md-8 col-md-offset-4">
                <div class="row">
                    <div class="col-md-3 col-md-offset-5 col-sm-3 col-sm-offset-5 col-xs-12">
                        <span class="btns-containers pull-right">
                            <a href="{% url 'news:article_detail' article.id %}" class="btn btn-secondary">Cancel</a>
                        </span>
                    </div>
                    <div class="col-md-4 col-sm-3 col-xs-12">
                        <span class="btns-containers pull-right">
                            <input class="btn btn-danger" id="update-article-form-submit" type="submit" value="Update article" />
                        </span>
                    </div>
                </div>
            </div>
        </div>

    </form>

</div>

{% endblock news_container %}

{% block extrafoot %}
{% comment %}
Empty because the jquery / bootstrap .js file have already been loaded in the extrahead block
{% endcomment %}
{% endblock extrafoot %}

news/templates/news/articles_list.html
{% extends "news/news-base.html" %}
{% load static %}

{% block news_container %}

<div class="col-md-12 col-sm-12 col-xs-12">

    <div class="row">
        <div class="col-md-8 col-md-offset-4 article-action">
            <h1>Articles list</h1>
        </div>
    </div>

    {% if articles|length %}

    <div class="row">
        {% for article in articles %}
            <div class="row">
                <div class="col-md-9 col-sm-9 col-xs-12 articles-list-row">
                <a href="{% url 'news:article_detail' article.id %}">{{ article.title }}</a>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-12 articles-list-row">
                <a href="{% url 'news:article_detail' article.id %}" class="btn btn-info">detail</a>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-12 articles-list-row">
                <a href="{% url 'news:article_update' article.id %}" class="btn btn-warning">edit</a>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-12 articles-list-row">
                <a href="{% url 'news:article_delete' article.id %}" class="btn btn-warning">delete</a>
                </div>
            </div>
        {% endfor %}
    </div>

    {% else %}

    <div class="row">
        <div class="col-md-8 col-md-offset-4 article-action">
            No articles found !
        </div>
    </div>

    {% endif %}

    <div class="row">
        <div class="col-md-8 col-md-offset-4 add-article-button">
            <a href="{% url 'news:article_create' %}" class="btn btn-warning">Add article</a>
        </div>
    </div>

</div>

{% endblock news_container %}

news/templates/news/news-base.html
{% extends "site-base.html" %}
{% load static %}

{% block title %}<title>{{ page_title }}</title>{% endblock title%}

{% block extrahead %}
 {{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'news/css/news.css' %}" />
{% endblock extrahead%}

{% block page_content %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="row" id="news-manage-container">
        {% block news_container %}
        {% endblock news_container %}
        </div>
    </div>
</div>
{% endblock page_content %}

templates/footer.html
<div id="footer">
    <div class="container-fluid">
        <p class="credit">Powered by <a href="https://www.djangoproject.com/">Django</a></p>
    </div>
</div>

templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
          <li class="dropdown active">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">News manager<span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li><a href="{% url 'news:articles_list' %}">Dashboard</a></li>
                  <li><a href="{% url 'news:article_create' %}">New article</a></li>
              </ul>
          </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

templates/site-base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    {% block title %}<title></title>{% endblock title%}
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/site-base.css' %}" />
    {% block extrahead %}{% endblock extrahead %}
    {% block extrastyle %}{% endblock extrastyle %}
  </head>
  <body>

  <div id="wrap">
      <!-- Static navbar -->

      {% include "navbar.html" %}

      <div class="container-fluid">
          <div class="row">
              <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1" >
              {% block page_content %}
              {% endblock page_content %}
              </div>
          </div>
      </div><!--/.container-fluid -->

      <div id="push"></div>

  </div><!--/.wrap -->

      {% include "footer.html" %}

      {% block extrafoot %}
      <script src="{% static 'jquery/jquery-1.12.4.min.js' %}"></script>
      <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
      {% endblock extrafoot %}

  </body>
</html>